#!/usr/bin/env node
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

export function localPaths(env = process.env) {
  const home = env.HOME ?? os.homedir();
  return {
    appSupport: env.PB_LOCAL_APP_SUPPORT ?? path.join(home, 'Library/Application Support/Local'),
    resources: env.PB_LOCAL_RESOURCES ?? '/Applications/Local.app/Contents/Resources/extraResources',
  };
}

const expandHome = (p, home) => (p.startsWith('~/') ? path.join(home, p.slice(2)) : p);
const readJson = (file, fallback) => { try { return JSON.parse(fs.readFileSync(file, 'utf8')); } catch { return fallback; } };
const real = (p) => { try { return fs.realpathSync(p); } catch { return path.resolve(p); } };

export function readSites(appSupport, home) {
  const sites = readJson(path.join(appSupport, 'sites.json'), null);
  if (!sites) return [];
  const statuses = readJson(path.join(appSupport, 'site-statuses.json'), {});
  return Object.values(sites).map((s) => {
    const rootPath = expandHome(s.path, home);
    return {
      id: s.id,
      name: s.name,
      domain: s.domain,
      rootPath,
      publicPath: path.join(rootPath, 'app/public'),
      phpVersion: s.services?.php?.version ?? null,
      running: statuses[s.id] === 'running',
    };
  });
}

export function findSiteForDir(sites, dir) {
  const d = real(dir);
  return sites.find((s) => {
    const root = real(s.rootPath);
    return d === root || d.startsWith(root + path.sep);
  }) ?? null;
}

export function findSiteByQuery(sites, q) {
  const lq = q.toLowerCase();
  return sites.find((s) => s.id === q || s.name?.toLowerCase() === lq || s.domain?.toLowerCase() === lq) ?? null;
}

export function platformKey(platform = process.platform, arch = process.arch) {
  if (platform === 'darwin') return arch === 'arm64' ? 'darwin-arm64' : 'darwin';
  return 'linux';
}

export function phpBinary(appSupport, version, platform = platformKey()) {
  const dir = path.join(appSupport, 'lightning-services');
  let entries = [];
  try { entries = fs.readdirSync(dir); } catch { return null; }
  const matches = entries.filter((e) => e.startsWith(`php-${version}+`)).sort().reverse();
  for (const m of matches) {
    const bin = path.join(dir, m, 'bin', platform, 'bin', 'php');
    if (fs.existsSync(bin)) return bin;
  }
  return null;
}

export const socketPath = (appSupport, id) => path.join(appSupport, 'run', id, 'mysql', 'mysqld.sock');
export const wpCliPhar = (resources) => path.join(resources, 'bin', 'wp-cli', 'wp-cli.phar');

export function resolveLocalSite({ cwd = process.cwd(), query, env = process.env } = {}) {
  const { appSupport, resources } = localPaths(env);
  const home = env.HOME ?? os.homedir();
  if (!fs.existsSync(path.join(appSupport, 'sites.json'))) {
    return { ok: false, notLocal: true, error: `Local by Flywheel not found (${appSupport}/sites.json missing).` };
  }
  const sites = readSites(appSupport, home);
  const names = sites.map((s) => s.name);
  const site = query ? findSiteByQuery(sites, query) : findSiteForDir(sites, cwd);
  if (!site) {
    const why = query ? `No Local site matches "${query}".` : `The current directory is not inside a Local site.`;
    return { ok: false, sites: names, error: `${why} Re-run with --site "<name>". Available: ${names.join(', ')}` };
  }
  const socket = socketPath(appSupport, site.id);
  if (!site.running || !fs.existsSync(socket)) {
    return { ok: false, halted: true, sites: names, error: `Start the site "${site.name}" in Local, then re-run.` };
  }
  const phpBin = phpBinary(appSupport, site.phpVersion);
  if (!phpBin) return { ok: false, error: `Local's PHP ${site.phpVersion} binary not found under ${appSupport}/lightning-services.` };
  const phar = wpCliPhar(resources);
  if (!fs.existsSync(phar)) return { ok: false, error: `Local's WP-CLI not found at ${phar}. Is Local installed in /Applications?` };
  return { ok: true, site: { ...site, phpBin, socket, phar } };
}

const q = (s) => `'${String(s).replaceAll("'", `'\\''`)}'`;

export function wrapperScript({ phpBin, socket, phar, publicPath }) {
  return [
    '#!/bin/sh',
    '# Generated by protoblocks-site-builder. Runs WP-CLI against a Local by Flywheel site.',
    `exec ${q(phpBin)} -d ${q(`mysqli.default_socket=${socket}`)} -d ${q(`pdo_mysql.default_socket=${socket}`)} -d memory_limit=512M ${q(phar)} ${q(`--path=${publicPath}`)} "$@"`,
    '',
  ].join('\n');
}

export function writeWrapper(file, site) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, wrapperScript(site), { mode: 0o755 });
  fs.chmodSync(file, 0o755);
  return file;
}

function parseArgs(argv) {
  const a = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith('--')) a[argv[i].slice(2)] = argv[++i];
    else a._.push(argv[i]);
  }
  return a;
}

function main(argv) {
  const a = parseArgs(argv);
  const r = resolveLocalSite({ cwd: a.cwd ?? process.cwd(), query: a.site });
  if (a._[0] === 'wrapper') {
    if (!a.out) { process.stderr.write('wrapper requires --out FILE\n'); process.exit(64); }
    if (!r.ok) { process.stdout.write(`${JSON.stringify(r, null, 2)}\n`); process.exit(2); }
    writeWrapper(a.out, r.site);
    process.stdout.write(`${JSON.stringify({ ok: true, wrapper: a.out, site: r.site }, null, 2)}\n`);
    return;
  }
  process.stdout.write(`${JSON.stringify(r, null, 2)}\n`);
  if (!r.ok) process.exit(2);
}

if (process.argv[1] && import.meta.url === pathToFileURL(fs.realpathSync(process.argv[1])).href) main(process.argv.slice(2));
