#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createWp, loadRuntime, WP_SCRIPTS_DIR } from './wp.mjs';
import { statePath, updateState, setPath } from './state.mjs';

const NAME = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const COLOR = /^(#[0-9a-fA-F]{3,8}|(rgb|rgba|hsl|hsla|oklch|oklab|color)\([^;{}]+\)|transparent|currentColor)$/;
const LENGTH = /^(0|-?\d*\.?\d+(px|rem|em|%|vw|vh|ch)|(clamp|calc|min|max)\([^;{}]+\))$/;
const UNITLESS = /^-?\d*\.?\d+$/;
const SAFE = (v) => typeof v === 'string' && v.trim() !== '' && !/[;{}]/.test(v);
const DEFAULT_FALLBACK = 'ui-sans-serif, system-ui, sans-serif';

export function validateTokens(t) {
  const errors = [];
  const group = (key, check) => {
    if (t[key] === undefined) return;
    if (typeof t[key] !== 'object' || t[key] === null || Array.isArray(t[key])) { errors.push(`${key}: must be an object`); return; }
    for (const [name, value] of Object.entries(t[key])) {
      if (!NAME.test(name)) errors.push(`${key}.${name}: invalid name (use lowercase-kebab-case)`);
      const problem = check(value);
      if (problem) errors.push(`${key}.${name}: ${problem}`);
    }
  };
  if (!t.colors || typeof t.colors !== 'object' || !Object.keys(t.colors).length) errors.push('colors: at least one color is required');
  group('colors', (v) => (SAFE(v) && COLOR.test(v.trim()) ? null : `invalid color ${JSON.stringify(v)}`));
  group('fonts', (v) => {
    if (!v || !SAFE(v.family) || /["']/.test(v.family)) return 'needs a "family" string without quotes';
    if (v.fallback !== undefined && !SAFE(v.fallback)) return 'invalid fallback';
    if (v.google !== undefined && !(Array.isArray(v.google) && v.google.every((w) => Number.isInteger(w) && w >= 100 && w <= 900))) return 'google must be an array of weights 100–900';
    return null;
  });
  group('type', (v) => {
    const size = typeof v === 'string' ? v : v?.size;
    if (!SAFE(size) || !LENGTH.test(size)) return `invalid size ${JSON.stringify(size)}`;
    if (typeof v === 'object') {
      if (v.lineHeight !== undefined && !(SAFE(String(v.lineHeight)) && (UNITLESS.test(String(v.lineHeight)) || LENGTH.test(String(v.lineHeight))))) return 'invalid lineHeight';
      if (v.letterSpacing !== undefined && !(SAFE(v.letterSpacing) && LENGTH.test(v.letterSpacing))) return 'invalid letterSpacing';
      if (v.fontWeight !== undefined && !/^[1-9]00$/.test(String(v.fontWeight))) return 'invalid fontWeight';
    }
    return null;
  });
  group('radii', (v) => (SAFE(v) && LENGTH.test(v) ? null : `invalid length ${JSON.stringify(v)}`));
  group('spacing', (v) => (SAFE(v) && LENGTH.test(v) ? null : `invalid length ${JSON.stringify(v)}`));
  group('shadows', (v) => (SAFE(v) ? null : `invalid shadow ${JSON.stringify(v)}`));
  return errors;
}

const fontStack = (f) => `"${f.family}", ${f.fallback ?? DEFAULT_FALLBACK}`;
const title = (k) => k.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');

export function renderTailwindTheme(t) {
  const lines = [
    '/*',
    ' * Design tokens — generated by protoblocks-site-builder (tokens.mjs apply).',
    ' * Re-applying tokens overwrites this file. Each token becomes a Tailwind utility',
    ' * (e.g. --color-accent → bg-accent, --text-h1 → text-h1, --radius-card → rounded-card).',
    ' */',
    '@theme {',
  ];
  const section = (label, entries) => { if (entries.length) lines.push(`  /* ${label} */`, ...entries.map((e) => `  ${e}`), ''); };
  section('Colors', Object.entries(t.colors ?? {}).map(([k, v]) => `--color-${k}: ${v};`));
  section('Fonts', Object.entries(t.fonts ?? {}).map(([k, f]) => `--font-${k}: ${fontStack(f)};`));
  section('Type scale', Object.entries(t.type ?? {}).flatMap(([k, v]) => {
    if (typeof v === 'string') return [`--text-${k}: ${v};`];
    const out = [`--text-${k}: ${v.size};`];
    if (v.lineHeight !== undefined) out.push(`--text-${k}--line-height: ${v.lineHeight};`);
    if (v.letterSpacing !== undefined) out.push(`--text-${k}--letter-spacing: ${v.letterSpacing};`);
    if (v.fontWeight !== undefined) out.push(`--text-${k}--font-weight: ${v.fontWeight};`);
    return out;
  }));
  section('Radii', Object.entries(t.radii ?? {}).map(([k, v]) => `--radius-${k}: ${v};`));
  section('Shadows', Object.entries(t.shadows ?? {}).map(([k, v]) => `--shadow-${k}: ${v};`));
  section('Spacing', Object.entries(t.spacing ?? {}).map(([k, v]) => `--spacing-${k}: ${v};`));
  if (lines.at(-1) === '') lines.pop();
  lines.push('}', '');
  return lines.join('\n');
}

export function mergeThemeJson(json, t) {
  const out = structuredClone(json);
  out.settings ??= {};
  if (t.colors) {
    out.settings.color ??= {};
    out.settings.color.palette = Object.entries(t.colors).map(([slug, color]) => ({ slug, name: title(slug), color }));
  }
  if (t.fonts || t.type) out.settings.typography ??= {};
  if (t.fonts) {
    out.settings.typography.fontFamilies = Object.entries(t.fonts).map(([slug, f]) => ({ slug, name: f.family, fontFamily: fontStack(f) }));
  }
  if (t.type) {
    out.settings.typography.fontSizes = Object.entries(t.type).map(([slug, v]) => ({ slug, name: title(slug), size: typeof v === 'string' ? v : v.size }));
  }
  return out;
}

export function googleFontsUrl(t) {
  const fams = Object.values(t.fonts ?? {}).filter((f) => Array.isArray(f.google) && f.google.length);
  if (!fams.length) return null;
  const parts = fams.map((f) => `family=${f.family.trim().replace(/\s+/g, '+')}:wght@${[...new Set(f.google)].sort((a, b) => a - b).join(';')}`);
  return `https://fonts.googleapis.com/css2?${parts.join('&')}&display=swap`;
}

const IMPORT_RE = /^[ \t]*@import url\("https:\/\/fonts\.googleapis\.com[^"]*"\);[ \t]*\n?/gm;

export function rewriteFontImport(css, t) {
  const url = googleFontsUrl(t);
  const line = url ? `@import url("${url}");\n` : '';
  if (IMPORT_RE.test(css)) {
    IMPORT_RE.lastIndex = 0;
    let first = true;
    return css.replace(IMPORT_RE, () => { const r = first ? line : ''; first = false; return r; });
  }
  if (!line) return css;
  const end = css.indexOf('*/');
  return end === -1 ? `${line}${css}` : `${css.slice(0, end + 2)}\n${line}${css.slice(end + 2).replace(/^\n/, '')}`;
}

export function applyTokens(themeDir, t) {
  const errors = validateTokens(t);
  if (errors.length) {
    const e = new Error(`Invalid tokens:\n- ${errors.join('\n- ')}`);
    e.code = 'ETOKENS';
    throw e;
  }
  const tw = path.join(themeDir, 'tailwind-theme.css');
  const tj = path.join(themeDir, 'theme.json');
  const st = path.join(themeDir, 'style.css');
  fs.writeFileSync(tw, renderTailwindTheme(t));
  fs.writeFileSync(tj, `${JSON.stringify(mergeThemeJson(JSON.parse(fs.readFileSync(tj, 'utf8')), t), null, '\t')}\n`);
  fs.writeFileSync(st, rewriteFontImport(fs.readFileSync(st, 'utf8'), t));
  return { written: ['tailwind-theme.css', 'theme.json', 'style.css'] };
}

function main(argv) {
  const [cmd, themeDir, file] = argv;
  if (cmd !== 'apply' || !themeDir || !file) { process.stderr.write('Usage: node tokens.mjs apply <themeDir> <tokens.json> [--no-compile]\n'); process.exit(64); }
  const t = JSON.parse(fs.readFileSync(file, 'utf8'));
  const { written } = applyTokens(themeDir, t);
  let compiled = null;
  if (!argv.includes('--no-compile')) {
    compiled = createWp(loadRuntime(themeDir)).evalFile(path.join(WP_SCRIPTS_DIR, 'tailwind.php'), ['compile']);
  }
  if (fs.existsSync(statePath(themeDir))) updateState(themeDir, (s) => { setPath(s, 'site.tokens', t); });
  process.stdout.write(`${JSON.stringify({ written, compiled }, null, 2)}\n`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(fs.realpathSync(process.argv[1])).href) {
  try { main(process.argv.slice(2)); } catch (e) { process.stderr.write(`${e.code ? `[${e.code}] ` : ''}${e.message}\n`); process.exit(1); }
}
