#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createWp, loadThemeRuntime, WP_SCRIPTS_DIR } from './wp.mjs';
import { assertFork } from './guards.mjs';
import { statePath, updateState, setPath } from './state.mjs';

const NAME = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const COLOR = /^(#[0-9a-fA-F]{3,8}|(rgb|rgba|hsl|hsla|oklch|oklab|color)\([A-Za-z0-9 .,%+\-*\/()#]+\)|transparent|currentColor)$/;
const LENGTH = /^(0|-?\d*\.?\d+(px|rem|em|%|vw|vh|ch)|(clamp|calc|min|max)\([A-Za-z0-9 .,%+\-*\/()#]+\))$/;
const UNITLESS = /^-?\d*\.?\d+$/;
// Printable ASCII only (rejects tab, NUL, DEL, newlines, U+2028/9, \v, \f, non-ASCII), plus CSS-structure characters.
const UNSAFE = /[^\x20-\x7e]|[;{}\\"'!<>]|\/\*|\*\/|@|url\(/i;
// Shadows are free text, so only a closed set of characters is accepted.
const SHADOW = /^[A-Za-z0-9 .,%#()\-+/]+$/;
// Parentheses must never close more than they open, and must end balanced.
const balanced = (v) => {
  let depth = 0;
  for (const ch of v) {
    if (ch === '(') depth += 1;
    else if (ch === ')' && --depth < 0) return false;
  }
  return depth === 0;
};
// Single value (colour/length): at most one top-level call, e.g. rejects `rgb(1)(2)`.
const singleCall = (v) => {
  let depth = 0;
  const s = v.trim();
  for (let i = 0; i < s.length; i += 1) {
    if (s[i] === '(') depth += 1;
    else if (s[i] === ')') { depth -= 1; if (depth === 0 && i !== s.length - 1) return false; }
  }
  return true;
};
const SAFE = (v) => typeof v === 'string' && v.trim() === v && v !== '' && !UNSAFE.test(v) && balanced(v);
const SINGLE = (v) => SAFE(v) && singleCall(v);
const FAMILY = /^[A-Za-z0-9][A-Za-z0-9 \-]{0,60}$/;
const FALLBACK_ITEM = /^[A-Za-z0-9 \-]+$/;
const GENERIC = new Set(['serif', 'sans-serif', 'monospace', 'cursive', 'fantasy', 'system-ui', 'ui-serif', 'ui-sans-serif', 'ui-monospace', 'ui-rounded', 'emoji', 'math', 'fangsong']);
const fallbackOk = (v) => SAFE(v) && v.split(',').every((i) => FALLBACK_ITEM.test(i.trim()));
const DEFAULT_FALLBACK = 'ui-sans-serif, system-ui, sans-serif';

export function validateTokens(t) {
  if (!t || typeof t !== 'object' || Array.isArray(t)) return ['tokens: must be an object'];
  const errors = [];
  const group = (key, check) => {
    if (t[key] === undefined) return;
    if (typeof t[key] !== 'object' || t[key] === null || Array.isArray(t[key])) { errors.push(`${key}: must be an object`); return; }
    for (const [name, value] of Object.entries(t[key])) {
      if (!NAME.test(name)) errors.push(`${key}.${name}: invalid name (use lowercase-kebab-case)`);
      const problem = check(value);
      if (problem) errors.push(`${key}.${name}: ${problem}`);
    }
  };
  if (!t.colors || typeof t.colors !== 'object' || !Object.keys(t.colors).length) errors.push('colors: at least one color is required');
  group('colors', (v) => (SINGLE(v) && COLOR.test(v.trim()) ? null : `invalid color ${JSON.stringify(v)}`));
  group('fonts', (v) => {
    if (!v || typeof v.family !== 'string' || !FAMILY.test(v.family)) return 'invalid family (letters, digits, spaces and hyphens only, max 61 chars)';
    if (v.fallback !== undefined && !fallbackOk(v.fallback)) return 'invalid fallback';
    if (v.google !== undefined && !(Array.isArray(v.google) && v.google.every((w) => Number.isInteger(w) && w >= 100 && w <= 900))) return 'google must be an array of weights 100–900';
    return null;
  });
  group('type', (v) => {
    const size = typeof v === 'string' ? v : v?.size;
    if (!SINGLE(size) || !LENGTH.test(size)) return `invalid size ${JSON.stringify(size)}`;
    if (typeof v === 'object') {
      if (v.lineHeight !== undefined && !(SINGLE(String(v.lineHeight)) && (UNITLESS.test(String(v.lineHeight)) || LENGTH.test(String(v.lineHeight))))) return 'invalid lineHeight';
      if (v.letterSpacing !== undefined && !(SINGLE(v.letterSpacing) && LENGTH.test(v.letterSpacing))) return 'invalid letterSpacing';
      if (v.fontWeight !== undefined && !/^[1-9]00$/.test(String(v.fontWeight))) return 'invalid fontWeight';
    }
    return null;
  });
  group('radii', (v) => (SINGLE(v) && LENGTH.test(v) ? null : `invalid length ${JSON.stringify(v)}`));
  group('spacing', (v) => (SINGLE(v) && LENGTH.test(v) ? null : `invalid length ${JSON.stringify(v)}`));
  group('shadows', (v) => (SAFE(v) && SHADOW.test(v) ? null : `invalid shadow ${JSON.stringify(v)}`));
  return errors;
}

const fallbackStack = (fb) => fb.split(',').map((i) => i.trim()).map((i) => (GENERIC.has(i) ? i : `"${i}"`)).join(', ');
const fontStack = (f) => `"${f.family.trim()}", ${fallbackStack(f.fallback ?? DEFAULT_FALLBACK)}`;
const title = (k) => k.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');

export function renderTailwindTheme(t) {
  const lines = [
    '/*',
    ' * Design tokens — generated by protoblocks-site-builder (tokens.mjs apply).',
    ' * Re-applying tokens overwrites this file. Each token becomes a Tailwind utility',
    ' * (e.g. --color-accent → bg-accent, --text-h1 → text-h1, --radius-card → rounded-card).',
    ' */',
    '@theme {',
  ];
  const section = (label, entries) => { if (entries.length) lines.push(`  /* ${label} */`, ...entries.map((e) => `  ${e}`), ''); };
  section('Colors', Object.entries(t.colors ?? {}).map(([k, v]) => `--color-${k}: ${v};`));
  section('Fonts', Object.entries(t.fonts ?? {}).map(([k, f]) => `--font-${k}: ${fontStack(f)};`));
  section('Type scale', Object.entries(t.type ?? {}).flatMap(([k, v]) => {
    if (typeof v === 'string') return [`--text-${k}: ${v};`];
    const out = [`--text-${k}: ${v.size};`];
    if (v.lineHeight !== undefined) out.push(`--text-${k}--line-height: ${v.lineHeight};`);
    if (v.letterSpacing !== undefined) out.push(`--text-${k}--letter-spacing: ${v.letterSpacing};`);
    if (v.fontWeight !== undefined) out.push(`--text-${k}--font-weight: ${v.fontWeight};`);
    return out;
  }));
  section('Radii', Object.entries(t.radii ?? {}).map(([k, v]) => `--radius-${k}: ${v};`));
  section('Shadows', Object.entries(t.shadows ?? {}).map(([k, v]) => `--shadow-${k}: ${v};`));
  section('Spacing', Object.entries(t.spacing ?? {}).map(([k, v]) => `--spacing-${k}: ${v};`));
  if (lines.at(-1) === '') lines.pop();
  lines.push('}', '');
  return lines.join('\n');
}

// The font used for body text: an explicit `body` font, else `sans`, `text`, `base`, else the first font.
export function bodyFontSlug(t) {
  const keys = Object.keys(t?.fonts ?? {});
  if (!keys.length) return null;
  return ['body', 'sans', 'text', 'base'].find((k) => keys.includes(k)) ?? keys[0];
}

// WordPress kebab-cases preset slugs for CSS variables (letters and digits split: "sans2" -> "sans-2").
export const presetVar = (slug) => `var(--wp--preset--font-family--${slug.match(/[a-z]+|[0-9]+/g).join('-')})`;

export function mergeThemeJson(json, t) {
  const out = structuredClone(json);
  out.settings ??= {};
  if (t.colors) {
    out.settings.color ??= {};
    out.settings.color.palette = Object.entries(t.colors).map(([slug, color]) => ({ slug, name: title(slug), color }));
  }
  if (t.fonts || t.type) out.settings.typography ??= {};
  if (t.fonts) {
    out.settings.typography.fontFamilies = Object.entries(t.fonts).map(([slug, f]) => ({ slug, name: f.family, fontFamily: fontStack(f) }));
    const body = bodyFontSlug(t);
    if (body) {
      out.styles ??= {};
      out.styles.typography ??= {};
      out.styles.typography.fontFamily = presetVar(body);
    }
  }
  if (t.type) {
    out.settings.typography.fontSizes = Object.entries(t.type).map(([slug, v]) => ({ slug, name: title(slug), size: typeof v === 'string' ? v : v.size }));
  }
  return out;
}

export const BODY_FONT_START = '/* >>> protoblocks: body font (managed by tokens.mjs apply; change the tokens instead) */';
export const BODY_FONT_END = '/* <<< protoblocks: body font */';
const FONT_DECL = /font-family\s*:[^;{}]*;?/;

/**
 * Point the theme's top-level `body { font-family: … }` rule at `stack`. The first time, the rule is
 * wrapped in managed markers; later runs only rewrite the declaration inside them (idempotent).
 * Returns `{ css, warning? }`; when no such rule exists the CSS is returned unchanged with a warning.
 */
export function rewriteBodyFont(css, stack) {
  const decl = `font-family: ${stack};`;
  const start = css.indexOf(BODY_FONT_START);
  const end = start === -1 ? css.indexOf(BODY_FONT_END) : css.indexOf(BODY_FONT_END, start);
  if (start !== -1 && end !== -1) {
    const region = css.slice(start + BODY_FONT_START.length, end);
    if (!FONT_DECL.test(region)) return { css, warning: 'style.css: the managed body font region has no font-family declaration; left unchanged.' };
    return { css: `${css.slice(0, start + BODY_FONT_START.length)}${region.replace(FONT_DECL, decl)}${css.slice(end)}` };
  }
  if (start !== -1 || end !== -1) return { css, warning: 'style.css: broken protoblocks body font markers; left unchanged (fix them by hand).' };
  const rules = /^body\s*\{[^{}]*\}/gm;
  for (let m = rules.exec(css); m; m = rules.exec(css)) {
    if (!FONT_DECL.test(m[0])) continue;
    const rule = m[0].replace(FONT_DECL, decl);
    return { css: `${css.slice(0, m.index)}${BODY_FONT_START}\n${rule}\n${BODY_FONT_END}${css.slice(m.index + m[0].length)}` };
  }
  return { css, warning: 'style.css has no top-level `body { font-family: … }` rule; the body font comes only from theme.json styles.typography.fontFamily.' };
}

export function googleFontsUrl(t) {
  const fams = Object.values(t.fonts ?? {}).filter((f) => Array.isArray(f.google) && f.google.length);
  if (!fams.length) return null;
  const parts = fams.map((f) => `family=${encodeURIComponent(f.family.trim()).replace(/%20/g, '+')}:wght@${[...new Set(f.google)].sort((a, b) => a - b).join(';')}`);
  return `https://fonts.googleapis.com/css2?${parts.join('&')}&display=swap`;
}

const IMPORT_RE = /^[ \t]*@import url\("https:\/\/fonts\.googleapis\.com[^"]*"\);[ \t]*\n?/gm;

export function rewriteFontImport(css, t) {
  const url = googleFontsUrl(t);
  const line = url ? `@import url("${url}");\n` : '';
  if (IMPORT_RE.test(css)) {
    IMPORT_RE.lastIndex = 0;
    let first = true;
    return css.replace(IMPORT_RE, () => { const r = first ? line : ''; first = false; return r; });
  }
  if (!line) return css;
  const end = css.indexOf('*/');
  return end === -1 ? `${line}${css}` : `${css.slice(0, end + 2)}\n${line}${css.slice(end + 2).replace(/^\n/, '')}`;
}

export function applyTokens(themeDir, t) {
  assertFork(themeDir);
  const errors = validateTokens(t);
  if (errors.length) {
    const e = new Error(`Invalid tokens:\n- ${errors.join('\n- ')}`);
    e.code = 'ETOKENS';
    throw e;
  }
  const tw = path.join(themeDir, 'tailwind-theme.css');
  const tj = path.join(themeDir, 'theme.json');
  const st = path.join(themeDir, 'style.css');
  const warnings = [];
  // Read and compute everything first so a missing/unparseable input throws before any write.
  let style = rewriteFontImport(fs.readFileSync(st, 'utf8'), t);
  const body = bodyFontSlug(t);
  if (body) {
    const r = rewriteBodyFont(style, fontStack(t.fonts[body]));
    style = r.css;
    if (r.warning) warnings.push(r.warning);
  }
  const outputs = [
    [tw, renderTailwindTheme(t)],
    [tj, `${JSON.stringify(mergeThemeJson(JSON.parse(fs.readFileSync(tj, 'utf8')), t), null, '\t')}\n`],
    [st, style],
  ];
  for (const [file, content] of outputs) fs.writeFileSync(`${file}.tmp`, content);
  for (const [file] of outputs) fs.renameSync(`${file}.tmp`, file);
  return { written: ['tailwind-theme.css', 'theme.json', 'style.css'], ...(warnings.length ? { warnings } : {}) };
}

export function runApply(themeDir, t, { compile } = {}) {
  const { written, warnings } = applyTokens(themeDir, t);
  let compiled = null;
  if (compile) {
    compiled = compile();
    if (!compiled || compiled.success === false) {
      const e = new Error(`Tailwind compile failed: ${compiled?.message ?? compiled?.error ?? JSON.stringify(compiled)}`);
      e.code = 'ECOMPILE';
      throw e;
    }
  }
  if (fs.existsSync(statePath(themeDir))) updateState(themeDir, (s) => { setPath(s, 'site.tokens', t); });
  return { written, compiled, ...(warnings ? { warnings } : {}) };
}

function main(argv) {
  const [cmd, themeDir, file] = argv;
  if (cmd !== 'apply' || !themeDir || !file) { process.stderr.write('Usage: node tokens.mjs apply <themeDir> <tokens.json> [--no-compile]\n'); process.exit(64); }
  const rt = loadThemeRuntime(themeDir);
  const t = JSON.parse(fs.readFileSync(file, 'utf8'));
  const compile = argv.includes('--no-compile') ? null : () => createWp(rt).evalFile(path.join(WP_SCRIPTS_DIR, 'tailwind.php'), ['compile']);
  process.stdout.write(`${JSON.stringify(runApply(themeDir, t, { compile }), null, 2)}\n`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(fs.realpathSync(process.argv[1])).href) {
  try { main(process.argv.slice(2)); } catch (e) { process.stderr.write(`${e.code ? `[${e.code}] ` : ''}${e.message}\n`); process.exit(1); }
}
